### ISSUE TITLE
Feature Request:  presets for libraries

### ISSUE THREAD

**Issue by mizzle-mo** [easy-webpack/core#10]
config-library-amd(namedExport?: "lodash") if left blank the module would not have a named export
config-library-umd(namedExport?: "lodash") if left blank the module would not have a named export
config-library-commonjs() 
config-library-system()
config-library-var(globalVar: "lodash" ) if left blank would need to throw or set a default like "mylib" 

See the [webpack documentation](https://webpack.github.io/docs/configuration.html#output-library) for more info, but you probably have the docs memorized at this point lol.  

I know this is trivial to do now with easy-webpack using the object merging, but it would be nice to have it available with just a quick download of a preset..  It would save a trip to the docs.  Especially if the parameters were typed, so intellisense/code-completion would show what the presets are expecting.

Please consider.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/155558844627395)

**Comment by mizzle-mo** [comment]
Just realized it might be easier to implement as one preset:

config-output-library({target: "umd", namedExport: "lodash"})

I would be fine with either one.  I do think making them separate would help with discoverability, but there are pros and cons to doing it both ways.

**Comment by niieani** [comment]
Makes sense. Would you be interested in maintaining this package if I create the initial repo?

**Comment by mizzle-mo** [comment]
I'll maintain that piece.

**Comment by mizzle-mo** [comment]
[config-output-library](https://github.com/mike-morrison/config-output-library)

@niieani I feel like it could be simplified greatly.  I felt it was important to notify the user on invalid input so I am throwing exceptions and using console.warn.  I could not find an example in the other projects I looked at on how to handle invalid input.  

Definitely looking for any advice on simplifying it as a learning exercise.  I am not a huge fan of switch, but it appeared to be the best tool for the job.  Still new to Open Source, and my TS/JS skills are not master level yet.  :)  Any feedback you have would be greatly appreciated.

Tests are all passing on my end.  I added cross-env as seen in the package.json for the test and build scripts.  This enables Windows developers to contribute, mainly me.

Thoughts?

**Comment by niieani** [comment]
Looks very thorough! Fantastic job, @mike-morrison.
I've forked config-output-library to easy-webpack and [gave you permission](https://github.com/easy-webpack/config-output-library/invitations) to the fork. 

I'll publish this today.

**Comment by niieani** [comment]
One note, please use the AngularJS Commit Message Conventions in the future commits. Also we don't need `version` field set in GitHub since it's set by the CI runner. More info on both things [here](https://github.com/easy-webpack/core#contributing).

**Comment by niieani** [comment]
@mike-morrison Published!
