### ISSUE TITLE
provideplugin

### ISSUE THREAD

**Issue by smithaitufe** [easy-webpack/core#14]
Please how do I use provideplugin with easy-webpack? I feel a list of the functions in (@easy-webpack/core) will help

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/160789121923608)

**Comment by niieani** [comment]
I see this is already closed, did you manage to find the solution?

**Comment by smithaitufe** [comment]
Yeah. I read through the doc and noticed I will need to require WebPack which in turn gave me access to the provide plug in. The easywebpack examples were helpful. Thanks

**Comment by niieani** [comment]
👍 awesome
