### ISSUE TITLE
Need Documentation - Aurelia-auth and Url-loader

### ISSUE THREAD

**Issue by xavica** [easy-webpack/core#15]
How to add aurelia-auth, aurelia-validate and url-loader?

Previously we had some issue with aurelia-dialog and we did some tweaking to make it working.
module: {
        loaders: [
            { test: /.css?$/, loader: 'style!css', exclude: /aurelia-dialog/ },
            { test: /.css?$/, loader: 'raw', include: /aurelia-dialog/ },
            { test: /.html$/, loader: 'raw' },
            { test: /.woff2(\?v=[0-9].[0-9].[0-9])?$/, loader: 'url-loader? limit=10000&minetype=application/font-woff2' },
        ]
    }

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/161583338970215)

**Comment by niieani** [comment]
You don't need any tweaking right now. Just use it. Aurelia Auth might need resources defined, please refer to the documentation of Aurelia (Doc Hub on the main website).
As for url-loaders, you may use the [`config-fonts-and-images`](https://github.com/easy-webpack/config-fonts-and-images).
