### ISSUE TITLE
Need Documentation - Jquery Plugins

### ISSUE THREAD

**Issue by xavica** [easy-webpack/core#16]
Can you provide sample example for configuring jquery plugins.
planning to add nicescroll plugin into our source. eg. https://github.com/inuyaksa/jquery.nicescroll

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/162367514547497)

**Comment by niieani** [comment]
I've updated the `config-global-jquery`. Now it should be as simple as:

``` ts
import 'jquery.nicescroll'
```

**Comment by xavica** [comment]
Where to add the file references in package.json build section or some where

**Comment by niieani** [comment]
just `npm install jquery.nicescroll --save`...
