### ISSUE TITLE
How do I do "includesSubModules" with easy-webpack

### ISSUE THREAD

**Issue by Vaccano** [easy-webpack/core#18]
I need to something like this:

```
  new AureliaWebpackPlugin({
      includeSubModules: [
          {
              moduleId: 'aurelia-breeze'
          }
      ]
  }),
```

But with easy-webpack, the `AureliaWebpackPlugin` does not seem to be available in the `webpack.config.js` file.

**Is there an alternate way to setup aurelia-breeze that I have missed?**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/165758049941294)

**Comment by Vaccano** [comment]
I just realized that easy-webpack probably does not know anything about the AurealiaWebpackPlugin.  

I added it and it compiled just fine.  (Did not work to let me use aurelia-breeze, but I doubt that has anything to do with easy-webpack.  (I am closing this.  Sorry for the extra chatter.)

**Comment by niieani** [comment]
`includeSubModules` was deprecated. You might want to use build resources instead. See either the The Hub docs on Webpack, the readme of skeleton-navigation-webpack.
Also, there's `easy-webpack/config-aurelia` which includes AureliaWebpackPlugin.

**Comment by Vaccano** [comment]
Thank you for the response!

I went and read the docs that were on the hub and I am afraid I just don't get it.  I would suggest more info in that file.

Things I see as missing:
- What is a "build resource"?  It does not seem the same as includesSubModules.  
- Does this replace the `.plugin('aurelia-dialog')` that is found in main?
- How do I know what values to put into them to make my plugin work?  Meaning, if I have the source code for a plugin, what or where should I look to see what build resources it has?
- How do plugin developers declare their build resources?

**Comment by niieani** [comment]
See this section: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-webpack/6

You could also read this: https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack#resource-and-bundling-configuration

As to the why and what and more advanced info see this: https://github.com/aurelia/webpack-plugin#module-resource-resolution

If that still doesn't answer your questions I'll try to address them.
