### ISSUE TITLE
Fail to load  estraverse module.

### ISSUE THREAD

**Issue by Alaboudi1** [easy-webpack/core#19]
When I try to load estraverse module into my project using webpack-skeleton, I get this error.

/**~/estraverse/package.json
Module parse failed: C:\Users\abdulaziz\Downloads\newProject\life-code-webpack\node_modules\estraverse\package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       {
 @ ./~/estraverse/estraverse.js 837:22-47
 @ ./src ^.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aureliaerrors @ client:49sock.onmessage @ client:83EventTarget.dispatchEvent @ eventtarget.js:51(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:50WebSocketTransport.ws.onmessage @ websocket.js:35**

It is worth to mention this also happens with aurelia-cli setup, but works perfectly fine with jspm (skeleton-esnext).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/170434747694885)

**Comment by niieani** [comment]
Seems the estraverse module is trying to load a `json` file. You need the json-loader to be able to do that.
