### ISSUE TITLE
Facing issue in loading CUR type files

### ISSUE THREAD

**Issue by mariaantony-gnanasekaran** [easy-webpack/core#40]
I am currently  using [skeleton-esnext-webpack](https://github.com/aurelia/skeleton-navigation/tree/1.1.2/skeleton-esnext-webpack).In this index.html file ,I want to add an image of CUR type file.
so I configured my webpack.config as given below 
```
config = generateConfig(config,
  {
    module: {
      loaders: [
        {
          test: /\.(cur)(\?\S*)?$/,
          loader: 'url-loader?name=[name].[ext]&limit=10000'
        }
      ]
    }
  }
);
```
But unfortunately,I am getting error like this
``` 
WARNING in ./src/flower.cur
Module parse failed: E:\development\skeleton-navigation-1.1.2\skeleton-esnext-webpack\src\flower.cur Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia.
 ```

so please suggest me a solution to overcome from this problem.

**Comment by niieani** [comment]
did you solve your issue?

**Comment by mariaantony-gnanasekaran** [comment]
@niieani Yes ,I solved my issue by configuring webpack.config as

```
config = generateConfig(config,
  {
    module: {
      rules: [{
        test: /\.(png|gif|cur|jpg)$/, loader: 'url-loader', query: { limit: 8192 }
      }]
    }
  }
);
module.exports = stripMetadata(config)
```

**Comment by mariaantony-gnanasekaran** [comment]
@niieani [config-fonts-and-images@3.1.0](https://github.com/easy-webpack/config-fonts-and-images/releases/tag/v3.1.0) released in github. Could you please let me know when will the changes published in NPM.?
