### ISSUE TITLE
config-yaml contribution

### ISSUE THREAD

**Issue by jinwangchina** [easy-webpack/core#45]
I couldn't find configuration for yaml, so I created one (refer to link below). 
https://github.com/jinwangchina/config-yaml

I wonder if you want to fork it and put it into "easy-webpack" group so that I can change my package.json to use the official one "@easy-webpack/config-yaml" from "easy-webpack" group.

**Comment by niieani** [comment]
Thanks @jinwangchina. I've created an official fork and added you as a contributor there.
I'll release this under NPM as soon as I have the time.
