### ISSUE TITLE
Adding a new js framework difference from skeleton nav 1.0.0-beta.1.2.6 to 1.0.0-beta.3.0.0

### ISSUE THREAD

**Issue by delebash** [easy-webpack/core#5]
In skeleton-navigation-1.0.0-beta.1.2.6 to import the bootstrap framework you would just add 
`import 'bootstrap';`to your main.js.  I have looked everywhere and cannot find out how you are importing the bootstrap framework

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/152789135197814)

**Comment by niieani** [comment]
This question belongs to aurelia/skeleton-navigation. 
The import happens here:
https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/src/app.html#L2
