### ISSUE TITLE
Support for jquery-migrate 1.3.0

### ISSUE THREAD

**Issue by pratikpparikh** [easy-webpack/core#6]
Dear Contributor,

```
     Could you please add configuration to support jquery-migrate 1.3.0, thus allowing use of load in order with jquery 3.0.
```

Regards,
Pratik Parikh

**Comment by niieani** [comment]
You don't need easy-webpack to support this, you can add it yourself if needed by simply importing it in your code.

**Comment by pratikpparikh** [comment]
Basyli,

Can you point me to how?  Sorry very new to webpack and easy-webpack

On Mon, Jul 11, 2016 at 8:58 AM, Bazyli Brzóska notifications@github.com
wrote:

> You don't need easy-webpack to support this, you can add it yourself if
> needed by simply importing it in your code.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/easy-webpack/core/issues/6#issuecomment-231726627,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABHKaxixdol11enBvcEvL-PyhiOV8v2dks5qUj3mgaJpZM4JJVQ2
> .

## 

Pratik Parikh
- Mantra - Keep It Simple and Straightforward

**Comment by niieani** [comment]
The problem is actually neither related to webpack nor easy-webpack. One way to include jquery-migrate is to simply install `jquery-migrate` using `npm` and then add something like `import 'jquery-migrate'` to the entry file of your code (e.g. `index.js`).
