### ISSUE TITLE
Investigate ExtractTextPlugin not firing correctly with CSS loaders

### ISSUE THREAD

**Issue by niieani** [easy-webpack/core#8]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/151032607952727/153682370670227)

**Comment by delebash** [comment]
config-sass

Looking into this as best as I can.  How are you using the Spread operator in this line
`loaders: extractCss ? extractText.extract(...loaders.slice(1)) : loaders`

It is already an array so slice is already available.  I am not sure why but if you remove the Spread operator the extract works.

Interesting note is that without the Spread operator you get this value returned as the sass loader
{"remove":true,"id":1}!css!sass

With the Spread operator you get this value returned
`{"omit":1,"extract":true,"remove":true,"id":1}!css!sass`

Another note is that if I use extractText =true  on both the config-css and config-sass **that is not using the spread operator** only the sass file is extracted, other css files such as`import 'font-awesome/css/font-awesome.css';` in index.js file are not extracted

**Comment by niieani** [comment]
Fixed in https://github.com/easy-webpack/config-css/commit/7fa3a29cabc1e6c48da66962be2ba255f0740e07
